/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as PlayRouteImport } from './routes/play'
import { Route as ParentsRouteImport } from './routes/parents'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PurchasesIndexRouteImport } from './routes/purchases.index'
import { Route as PurchasesProductIdRouteImport } from './routes/purchases.$productId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentsRoute = ParentsRouteImport.update({
  id: '/parents',
  path: '/parents',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesIndexRoute = PurchasesIndexRouteImport.update({
  id: '/purchases/',
  path: '/purchases/',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesProductIdRoute = PurchasesProductIdRouteImport.update({
  id: '/purchases/$productId',
  path: '/purchases/$productId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/parents': typeof ParentsRoute
  '/play': typeof PlayRoute
  '/progress': typeof ProgressRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/purchases/$productId': typeof PurchasesProductIdRoute
  '/purchases/': typeof PurchasesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/parents': typeof ParentsRoute
  '/play': typeof PlayRoute
  '/progress': typeof ProgressRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/purchases/$productId': typeof PurchasesProductIdRoute
  '/purchases': typeof PurchasesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/parents': typeof ParentsRoute
  '/play': typeof PlayRoute
  '/progress': typeof ProgressRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/purchases/$productId': typeof PurchasesProductIdRoute
  '/purchases/': typeof PurchasesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/parents'
    | '/play'
    | '/progress'
    | '/sitemap.xml'
    | '/purchases/$productId'
    | '/purchases/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/parents'
    | '/play'
    | '/progress'
    | '/sitemap.xml'
    | '/purchases/$productId'
    | '/purchases'
  id:
    | '__root__'
    | '/'
    | '/onboarding'
    | '/parents'
    | '/play'
    | '/progress'
    | '/sitemap.xml'
    | '/purchases/$productId'
    | '/purchases/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OnboardingRoute: typeof OnboardingRoute
  ParentsRoute: typeof ParentsRoute
  PlayRoute: typeof PlayRoute
  ProgressRoute: typeof ProgressRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  PurchasesProductIdRoute: typeof PurchasesProductIdRoute
  PurchasesIndexRoute: typeof PurchasesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parents': {
      id: '/parents'
      path: '/parents'
      fullPath: '/parents'
      preLoaderRoute: typeof ParentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchases/': {
      id: '/purchases/'
      path: '/purchases'
      fullPath: '/purchases/'
      preLoaderRoute: typeof PurchasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchases/$productId': {
      id: '/purchases/$productId'
      path: '/purchases/$productId'
      fullPath: '/purchases/$productId'
      preLoaderRoute: typeof PurchasesProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OnboardingRoute: OnboardingRoute,
  ParentsRoute: ParentsRoute,
  PlayRoute: PlayRoute,
  ProgressRoute: ProgressRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  PurchasesProductIdRoute: PurchasesProductIdRoute,
  PurchasesIndexRoute: PurchasesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
